name: Building recovery

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

env:
  MANIFEST: https://gitlab.com/OrangeFox/Manifest.git
  MANIFEST_BRANCH: fox_9.0
  DEVICE: tulix
  DT_LINK: https://github.com/XelXen/ofrp-device_xiaomi_tulip.git
  DT_PATH: device/xiaomi/tulix
  TARGET: recoveryimage
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Initializing environment
         run: |
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
            docker rmi `docker images -q`
            sudo apt-get remove account-plugin-facebook account-plugin-flickr account-plugin-jabber account-plugin-salut account-plugin-twitter account-plugin-windows-live account-plugin-yahoo aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common mcp-account-manager-uoa python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix
            git config --global user.name "XelXen"
            git config --global user.email "xelxenfox@gmail.com"         
            sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* 
            sudo -E apt-get clean
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex curl  bison aria2
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            
       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST -b $MANIFEST_BRANCH --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
             repo sync -j16 --force-sync
             git clone $DT_LINK --depth=1 --single-branch $DT_PATH
             
       - name: Build
         run: |
              cd work
              . build/envsetup.sh && lunch omni_tulix-eng && export ALLOW_MISSING_DEPENDENCIES=true && export FOX_ADVANCED_SECURITY="1" && export FOX_ASH_IS_BASH="1" && export FOX_BUILD_DEBUG_MESSAGES="0" && export FOX_BUILD_TYPE="MATRIX" && export FOX_DEVICE="tulix" && export FOX_OUT_NAME="OrangeFox-R11.1-MATRIX-tulix" && export FOX_REPLACE_BUSYBOX_PS="1" && export FOX_USE_BASH_SHELL="1" && export FOX_USE_NANO_EDITOR="1" && export FOX_USE_TAR_BINARY="1" && export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER="1" && export FOX_USE_XZ_UTILS="1" && export FOX_USE_ZIP_BINARY="1" && export FOX_VARIANT="default" && export FOX_VERSION="MATRIX-11.1" && export OF_ALLOW_DISABLE_NAVBAR="0" && export OF_CLOCK_POS="2" && export OF_DISABLE_MIUI_OTA_BY_DEFAULT="1" && export OF_DONT_PATCH_ENCRYPTED_DEVICE="1" && export OF_FIX_OTA_UPDATE_MANUAL_FLASH_ERROR="1" && export OF_FORCE_MAGISKBOOT_BOOT_PATCH_MIUI="1" && export OF_HIDE_NOTCH="1" && export OF_LEGACY_SHAR512="1" && export OF_NO_SAMSUNG_SPECIAL="1" && export OF_OTA_BACKUP_STOCK_BOOT_IMAGE="1" && export OF_PATCH_AVB20="1" && export OF_QUICK_BACKUP_LIST="/boot;/data;/system_image;/vendor_image;" && export OF_REDUCE_DECRYPTION_TIMEOUT="1" && export OF_RUN_POST_FORMAT_PROCESS="1" && export OF_SCREEN_H="2280" && export OF_SKIP_MULTIUSER_FOLDERS_BACKUP="1" && export OF_STATUS_H="80" && export OF_STATUS_INDENT_LEFT="48" && export OF_STATUS_INDENT_RIGHT="48" && export OF_SUPPORT_ALL_BLOCK_OTA_UPDATES="1" && export OF_TARGET_DEVICES="tulix,twolip,tulip" && export OF_USE_MAGISKBOOT="1" && export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES="1" && export OF_USE_NEW_MAGISKBOOT="1" && export OF_USE_TWRP_SAR_DETECT="1" && export OF_NO_TREBLE_COMPATIBILITY_CHECK=1 && export OF_MAINTAINER="XelXen" && export OF_PATCH_AVB20=1 && export LC_ALL="C" && mka -j16 $TARGET
             
       - uses: actions/upload-artifact@v2
         with:
          name: OrangeFox-R11.1-MATRIX-tulix.zip
          path: work/out/target/product/*/OrangeFox*.zip

       - uses: actions/upload-artifact@v2
         with:
          name: recovery.img
          path: work/out/target/product/*/recovery.img